### ISSUE TITLE
Document how Elixir is interface with C

### ISSUE THREAD

**Issue by pallix** [nerves-project/nerves_uart#24]
Hi,

it would be great to put in the FAQ how the program is interfaced with C (port / NIFS / C node) and the security guarantees with regards to the supervisor if the C code crashes. If I understand correctly [ports](https://hexdocs.pm/elixir/Port.html) are used.

**Comment by fhunleth** [comment]
Ports are indeed used to isolate the Erlang VM from any weirdness when interacting with the serial port. Closing since I haven't had time to work on `nerves_uart` recently and I'm not quite sure what to add that's not already documented in the Erlang and Elixir docs. PRs are certainly welcome.
