### ISSUE TITLE
Use pid instead of serial port name

### ISSUE THREAD

**Issue by tallakt** [nerves-project/nerves_uart#38]
Hi. When reading serial data through messages (active: true), the data received is in the form ‘{:nerves_uart, port_name, data}’. Because og this, I need to maintain a map of name to pids, as pids are what I can use to send messages back to the receiving serial port. I would have expected and preferred the messages to be in the format:  ‘{:nerves_uart, pid, data}’. This could be implemented in a backeard compatible way by having an argument to ‘open’ such as: ‘open(pid, name, active: :format2)

**Comment by fhunleth** [comment]
I agree that's annoying. Please feel free to send a PR with this change.

**Comment by tallakt** [comment]
https://github.com/nerves-project/nerves_uart/pull/39
