### ISSUE TITLE
Program exits when framing is incorrect.

### ISSUE THREAD

**Issue by acrogenesis** [nerves-project/nerves_uart#41]
If we set the option for framing with `\n`, `framing: {Nerves.UART.Framing.Line, separator: "\n"}`, but send no new line we get this error:
```
** (exit) exited in: GenServer.call(#PID<0.166.0>, {:read, 3000}, 3100)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:834: GenServer.call/3
    (hello_uart) lib/hello_uart.ex:24: HelloUart.uart_loop/1
```

The example can be found in: https://github.com/DisruptiveAngels/uart-example/blob/d990251ce6fd4992f91c3fee490253e0f1a8d06d/lib/hello_uart.ex

**Comment by fhunleth** [comment]
Thanks for the error report and example. What OS and hardware are you using?

**Comment by acrogenesis** [comment]
```
macOS 10.13.4
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-
poll:false]
Elixir (1.6.4)
```
I think what's happening is that it's waiting for the `\n` but because it wasn't sent it just timeouts. Perhaps it should just send whats on the buffer or a timeout error.

**Comment by acrogenesis** [comment]
For testing this we run the example on my Mac and on another pc connected through USB/uart and on the pc we run Arduino to easily send messages without line ending, `\n`, and `\r\n`

**Comment by acrogenesis** [comment]
So I was debugging the error more and noticed I was using the version 1.0.1 when I updated it started working as expected
